@startuml fluxograma
|Batch Diário|
start
:Acessar pasta NotasNovas;
if (Existem novas imagens?) then (sim)
  if (Ainda ha imagens a serem processadas?) then (sim)
    :Executar pyzbar para extrair o qr code da imagem;
    :Extrair a chave de acesso do link do qr code;
    :Consultar chave de acesso no site da SEFAZ e extrair dados do cupom;
    :Atualizar banco de dados com dados do cupom fiscal;
    :Mover imagem processada para a pasta NotasTratadas;
  else (não)
    :Terminar;
  endif
else (não)
  :Aguardar próximo ciclo;
endif
stop

|Web App|
start
:Usuário acessa site;
:Insere termo de pesquisa;
:Consultar banco de dados;
:Exibir histórico de preços;
stop
@enduml
